package backupdest

import (
	"context"
	"strings"
	"testing"
	"time"
)

func TestLocalRoundTripAndList(t *testing.T) {
	d := NewLocal(t.TempDir())
	ctx := context.Background()
	if err := d.Put(ctx, "b1.campbk", []byte("one")); err != nil {
		t.Fatalf("put: %v", err)
	}
	objs, err := d.List(ctx)
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(objs) != 1 || objs[0].Name != "b1.campbk" || objs[0].Size != 3 {
		t.Fatalf("unexpected listing: %+v", objs)
	}
	if err := d.Delete(ctx, "b1.campbk"); err != nil {
		t.Fatalf("delete: %v", err)
	}
	if objs, _ := d.List(ctx); len(objs) != 0 {
		t.Errorf("still listed after delete: %+v", objs)
	}
	// Deleting what is already gone is success, not an error to handle at 3am.
	if err := d.Delete(ctx, "b1.campbk"); err != nil {
		t.Errorf("second delete: %v", err)
	}
	// Listing a destination that has never been written to is not an error.
	if _, err := NewLocal(t.TempDir() + "/never").List(ctx); err != nil {
		t.Errorf("list of an empty destination: %v", err)
	}
}

// PATH TRAVERSAL must be refused. Names are generated by the product, but delete
// also takes a name from a list an operator acts on, and "../../etc/passwd"
// reaching os.Remove is worth making impossible here rather than trusting callers.
func TestUnsafeNamesRefused(t *testing.T) {
	d := NewLocal(t.TempDir())
	ctx := context.Background()
	for _, bad := range []string{"", "../escape", "a/b", `a\b`, "..", "x/../../y"} {
		if err := d.Put(ctx, bad, []byte("x")); err == nil {
			t.Errorf("put accepted unsafe name %q", bad)
		}
		if err := d.Delete(ctx, bad); err == nil {
			t.Errorf("delete accepted unsafe name %q", bad)
		}
	}
}

// A half-written file must not appear as a backup.
func TestPartialWritesAreNotListed(t *testing.T) {
	dir := t.TempDir()
	d := NewLocal(dir)
	ctx := context.Background()
	if err := d.Put(ctx, "good.campbk", []byte("x")); err != nil {
		t.Fatal(err)
	}
	// Simulate an interrupted write leaving its temp file behind.
	if err := NewLocal(dir).Put(ctx, "other.campbk", []byte("y")); err != nil {
		t.Fatal(err)
	}
	if err := writeDotFile(dir, ".interrupted.campbk.part"); err != nil {
		t.Fatal(err)
	}
	objs, err := d.List(ctx)
	if err != nil {
		t.Fatal(err)
	}
	for _, o := range objs {
		if strings.HasPrefix(o.Name, ".") {
			t.Errorf("a partial file was listed as a backup: %q", o.Name)
		}
	}
	if len(objs) != 2 {
		t.Errorf("expected 2 backups, got %d: %+v", len(objs), objs)
	}
}

// Prune keeps the NEWEST n. Getting the ordering backwards would delete the
// backups you want and keep the ones you do not, silently.
func TestPruneKeepsNewest(t *testing.T) {
	d := &fakeDest{objs: []Object{
		{Name: "oldest", Modified: time.Now().Add(-72 * time.Hour)},
		{Name: "newest", Modified: time.Now()},
		{Name: "middle", Modified: time.Now().Add(-24 * time.Hour)},
	}}
	deleted, err := Prune(context.Background(), d, 2)
	if err != nil {
		t.Fatalf("prune: %v", err)
	}
	if len(deleted) != 1 || deleted[0] != "oldest" {
		t.Fatalf("prune deleted %v, want [oldest]", deleted)
	}
}

// keep <= 0 must mean "keep everything", not "delete everything". An unset config
// value is far likelier than a deliberate instruction to wipe the destination.
func TestPruneZeroKeepsEverything(t *testing.T) {
	d := &fakeDest{objs: []Object{{Name: "a"}, {Name: "b"}}}
	deleted, err := Prune(context.Background(), d, 0)
	if err != nil || len(deleted) != 0 {
		t.Fatalf("prune(0) deleted %v err=%v; it must delete nothing", deleted, err)
	}
	if len(d.deleted) != 0 {
		t.Fatalf("prune(0) called Delete: %v", d.deleted)
	}
	if _, err := Prune(context.Background(), d, -1); err != nil || len(d.deleted) != 0 {
		t.Fatal("prune(-1) must also delete nothing")
	}
}

// Secrets must not survive Redacted() — it feeds logs and API responses.
func TestRedactedRemovesEverySecret(t *testing.T) {
	s := Settings{
		Provider: "s3", Bucket: "b", AccessKey: "AKIA-visible",
		SecretKey: "super-secret", Password: "hunter2", PrivateKeyPEM: "-----BEGIN...",
	}
	r := s.Redacted()
	for name, v := range map[string]string{"SecretKey": r.SecretKey, "Password": r.Password, "PrivateKeyPEM": r.PrivateKeyPEM} {
		if v != "********" {
			t.Errorf("%s not redacted: %q", name, v)
		}
	}
	// Non-secrets must survive, or the UI cannot show what is configured.
	if r.Bucket != "b" || r.AccessKey != "AKIA-visible" || r.Provider != "s3" {
		t.Errorf("redaction removed non-secrets: %+v", r)
	}
}

type fakeDest struct {
	objs    []Object
	deleted []string
}

func (f *fakeDest) Put(context.Context, string, []byte) error { return nil }
func (f *fakeDest) List(context.Context) ([]Object, error)    { return f.objs, nil }
func (f *fakeDest) Delete(_ context.Context, n string) error {
	f.deleted = append(f.deleted, n)
	return nil
}
func (f *fakeDest) Describe() string { return "fake" }
